name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Calculating KNN distances
      id: calculating-knn-distances
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Calculating KNN distances
        setup-command: sudo -H pip3 install pytest pandas argparse
        command: pytest knn_test.py::test_knn_distances
        timeout: 10
        max-score: 40
    - name: Classifying Iris dataset
      id: classifying-iris-dataset
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Classifying Iris dataset
        setup-command: ''
        command: pytest knn_test.py::test_knn_classifier_accuracy
        timeout: 10
        max-score: 60
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        CALCULATING-KNN-DISTANCES_RESULTS: "${{steps.calculating-knn-distances.outputs.result}}"
        CLASSIFYING-IRIS-DATASET_RESULTS: "${{steps.classifying-iris-dataset.outputs.result}}"
      with:
        runners: calculating-knn-distances,classifying-iris-dataset
